In [3]:
import csv
import pandas as pd
import pickle
import re
from sklearn.model_selection import train_test_split
import spacy
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
import numpy as np
import os.path
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import cross_validate

In [4]:
data = pd.read_excel("Rest_Mex_2022.xlsx")
data.head(10)

Title  \
0                                       Pésimo lugar   
1                          No vayas a lugar de Eddie   
2                       Mala relación calidad-precio   
3                   Minusválido? ¡No te alojes aquí!   
4              Es una porqueria no pierdan su tiempo   
5                      El peor huevos Benedict jamás   
6  Definitivamente no volvería a hospedarme en Sa...   
7                                           Terrible   
8       Bebidas ADULTERADAS, FATAL mi experiencia!!!   
9                          Hotel ha ido cuesta abajo   

                                             Opinion  Polarity  Attraction  
0  Piensen dos veces antes de ir a este hotel, te...         1       Hotel  
1  Cuatro de nosotros fuimos recientemente a Eddi...         1  Restaurant  
2  seguiré corta y simple: limpieza\n- bad. Tengo...         1       Hotel  
3  Al reservar un hotel con multipropiedad Mayan ...         1       Hotel  
4  No pierdan su tiempo ni dinero, venimos porque...         1       Hotel  
5  Hoy teníamos el desayuno por segunda vez en po...         1  Restaurant  
6  El hotel en si no es malo, pero mi experiencia...         1       Hotel  
7  No estoy seguro de por qué este restaurante ti...         1  Restaurant  
8  Llegué a este hotel “por desgracia” mi reserva...         1       Hotel  
9  Hemos estado viniendo a Villa la Estancia dura...         1       Hotel

In [18]:
data['Opinion'][7693]

'Aunque me parece algo hipócrita el arte de Rivera (todo lo ve desde fuera desde una zona segura), debo reconocer que tiene algunas obras que me agradan. Este museo es interesante por el simple hecho de conocer el primer hogar que fuera de Rivera. Bastante fancy. Está chido si te gusta ver cosas antiguas.'

In [5]:
myTest = data.head(10000)
print(myTest)

                                      Title  \
0                              Pésimo lugar   
1                 No vayas a lugar de Eddie   
2              Mala relación calidad-precio   
3          Minusválido? ¡No te alojes aquí!   
4     Es una porqueria no pierdan su tiempo   
...                                     ...   
9995                               Vacacion   
9996                 Excelente y muy barato   
9997                      Mi lugar favorito   
9998                     Joysquad excelente   
9999               El hotel y sus empleados   

                                                Opinion  Polarity  Attraction  
0     Piensen dos veces antes de ir a este hotel, te...         1       Hotel  
1     Cuatro de nosotros fuimos recientemente a Eddi...         1  Restaurant  
2     seguiré corta y simple: limpieza\n- bad. Tengo...         1       Hotel  
3     Al reservar un hotel con multipropiedad Mayan ...         1       Hotel  
4     No pierdan su tiempo ni diner

# Normalizacion

In [20]:
# nlp = spacy.load("es_core_news_sm")

In [6]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

def lemmatize_token(token):
    lemmatizer = WordNetLemmatizer()
    return lemmatizer.lemmatize(token)

def tokenizar(doc):
    if type(doc) != type(""):
        print(doc)
        return ""

    # Tokenize the document
    tokens = word_tokenize(doc, language='spanish')

    # Remove stop words and lemmatize
    stop_words = set(stopwords.words('spanish'))
    filtered_tokens = [lemmatize_token(token) for token in tokens if token.lower() not in stop_words]

    # Join the filtered tokens into a string
    res = " ".join(filtered_tokens)

    return res

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sergi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sergi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sergi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [7]:
myTest['Opinion'] = myTest['Opinion'].apply(tokenizar)

nan


C:\Users\sergi\AppData\Local\Temp\ipykernel_2964\77379802.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myTest['Opinion'] = myTest['Opinion'].apply(tokenizar)


In [8]:
myTest

Title  \
0                              Pésimo lugar   
1                 No vayas a lugar de Eddie   
2              Mala relación calidad-precio   
3          Minusválido? ¡No te alojes aquí!   
4     Es una porqueria no pierdan su tiempo   
...                                     ...   
9995                               Vacacion   
9996                 Excelente y muy barato   
9997                      Mi lugar favorito   
9998                     Joysquad excelente   
9999               El hotel y sus empleados   

                                                Opinion  Polarity  Attraction  
0     Piensen do veces ir hotel , molestan , hijo se...         1       Hotel  
1     Cuatro recientemente Eddie 's Place . servicio...         1  Restaurant  
2     seguiré corta simple : limpieza - bad . insist...         1       Hotel  
3     reservar hotel multipropiedad Mayan grupo dije...         1       Hotel  
4     pierdan tiempo dinero , venimos boda aquí mism...         1       Hotel  
...                                                 ...       ...         ...  
9995  excelente lugar vacacionar , servicio primera ...         5       Hotel  
9996  Buena carne , tortilla recién hechas , queso f...         5  Restaurant  
9997  Siempre vamos , vamos seguido , comemos delici...         5  Restaurant  
9998  Lisbhet Torre Punta excelente servicio amable ...         5       Hotel  
9999  hotel samba mejor clase podrá ver hoteles mejo...         5       Hotel  

[10000 rows x 4 columns]

In [9]:
myTest['Polarity'].value_counts()

Polarity
4    5878
3    2121
2     730
5     724
1     547
Name: count, dtype: int64

In [25]:
result = myTest[myTest['Opinion']=="error"]

In [26]:
result

Empty DataFrame
Columns: [Title, Opinion, Polarity, Attraction]
Index: []

In [27]:
myTest['Title'] = myTest['Title'].apply(tokenizar)

2016-12-01 00:00:00
2015-05-01 00:00:00


C:\Users\sergi\AppData\Local\Temp\ipykernel_21960\745785095.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  myTest['Title'] = myTest['Title'].apply(tokenizar)


In [10]:
myTest

Title  \
0                              Pésimo lugar   
1                 No vayas a lugar de Eddie   
2              Mala relación calidad-precio   
3          Minusválido? ¡No te alojes aquí!   
4     Es una porqueria no pierdan su tiempo   
...                                     ...   
9995                               Vacacion   
9996                 Excelente y muy barato   
9997                      Mi lugar favorito   
9998                     Joysquad excelente   
9999               El hotel y sus empleados   

                                                Opinion  Polarity  Attraction  
0     Piensen do veces ir hotel , molestan , hijo se...         1       Hotel  
1     Cuatro recientemente Eddie 's Place . servicio...         1  Restaurant  
2     seguiré corta simple : limpieza - bad . insist...         1       Hotel  
3     reservar hotel multipropiedad Mayan grupo dije...         1       Hotel  
4     pierdan tiempo dinero , venimos boda aquí mism...         1       Hotel  
...                                                 ...       ...         ...  
9995  excelente lugar vacacionar , servicio primera ...         5       Hotel  
9996  Buena carne , tortilla recién hechas , queso f...         5  Restaurant  
9997  Siempre vamos , vamos seguido , comemos delici...         5  Restaurant  
9998  Lisbhet Torre Punta excelente servicio amable ...         5       Hotel  
9999  hotel samba mejor clase podrá ver hoteles mejo...         5       Hotel  

[10000 rows x 4 columns]

# Splitting

In [11]:
train, test = train_test_split(myTest, test_size=0.2)

In [12]:
train

Title  \
4097                                          Holidays   
2228  Hermosa propiedad ... servicio peor que la media   
4732                               Ruidosa, pero bueno   
2532         Demasiados saltamontes y camarones w/Head   
4397                                       sabor local   
...                                                ...   
9830                                Vistas increíbles!   
3899                              Esperaba un poco más   
757                Muy baja calidad por lo que se paga   
7833                             Mercado de Guanajuato   
1791                                    Decepcionante.   

                                                Opinion  Polarity  Attraction  
4097  Lugar acogedor bueno vacacionar . Solo servici...         4       Hotel  
2228  : Acabo volver PVR después estancia 5 noches 3...         3       Hotel  
4732  Grand Velas mejor sopa tortilla probado . inte...         4  Restaurant  
2532  bistec Mole saltamontes , gustaría alguien dic...         3  Restaurant  
4397  pequeño gran restaurante local simpáticos cama...         4  Restaurant  
...                                                 ...       ...         ...  
9830  Vimos atardecer vista increíble ! comida bebid...         5  Restaurant  
3899  hospedado Resort 19 22 septiembre 2014 aunque ...         4       Hotel  
757   tanta variedad alimentos . calidad alimentos d...         2       Hotel  
7833  sitio bueno comer gorditas comida callejera , ...         4  Attractive  
1791  dijeron Riviera Grill buen lugar comida mexica...         3  Restaurant  

[8000 rows x 4 columns]

In [13]:
test

Title  \
2660                                           Limitada   
2012                Bonito hotel con una playa marginal   
6424                              Vacaciones en familia   
9125                   Mirador inmejorable de la ciudad   
6801                               Un placer inesperado   
...                                                 ...   
4646  Hermoso complejo, pero las habitaciones son un...   
1838                    Bueno pero detalles que mejorar   
6761                                     Señal de wi fi   
3055                                     Mixed feelings   
3243                                   Muy pocas momias   

                                                Opinion  Polarity  Attraction  
2660  mejor servicio , inspiración menú == buena ubi...         3  Restaurant  
2012  hotel personal excepcionales . ubicación limit...         3       Hotel  
6424  hotel súper bien , atencion instalaciones padr...         4       Hotel  
9125  vista vale pena , además chiste subir pie hace...         4  Attractive  
6801  yendo mismos lugares años ... Bien esposa . gu...         4  Restaurant  
...                                                 ...       ...         ...  
4646  esposa visitamos Hard Rock Nuevo Vallarta viaj...         4       Hotel  
1838  Empezemos recepción , llegas personal amable ,...         3       Hotel  
6761  general hotel lindo , solo deben considerar am...         4       Hotel  
3055  I went there early in the morning , so there w...         3  Attractive  
3243  hicieron pocas pues entretiene rato si va ve c...         3  Attractive  

[2000 rows x 4 columns]

# Text Representations

In [43]:
vectorizador_binario = CountVectorizer(binary=True, token_pattern= r'(?u)\w\w+|\w\w+\n|\.')
vectorizador_frecuencia = CountVectorizer(token_pattern= r'(?u)\w\w+|\w\w+\n|\.')
vectorizador_tfidf = TfidfVectorizer()

In [44]:
train_vectorizado = vectorizador_tfidf.fit_transform(train['Opinion'])

In [45]:
test_vectorizado = vectorizador_tfidf.transform(test['Opinion'])

In [46]:
print(vectorizador_tfidf.get_feature_names_out())
print(train_vectorizado.toarray())
print(len(train_vectorizado.toarray()[0]))
print(len(vectorizador_tfidf.get_feature_names_out()))

['00' '000' '00am' ... 'útiles' 'útlimo' 'ĺlegaron']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
29552
29552


# Using Sentiment lexicons

In [18]:
def load_sel():
	#~ global lexicon_sel
	lexicon_sel = {}
	input_file = open('SEL_full.txt', 'r', encoding="utf-8")
	for line in input_file:
		#Las líneas del lexicon tienen el siguiente formato:
		#abundancia	0	0	50	50	0.83	Alegría
		
		palabras = line.split("\t")
		palabras[6]= re.sub('\n', '', palabras[6])
		pair = (palabras[6], palabras[5])
		if lexicon_sel:
			if palabras[0] not in lexicon_sel:
				lista = [pair]
				lexicon_sel[palabras[0]] = lista
			else:
				lexicon_sel[palabras[0]].append (pair)
		else:
			lista = [pair]
			lexicon_sel[palabras[0]] = lista
	input_file.close()
	del lexicon_sel['Palabra']; #Esta llave se inserta porque es parte del encabezado del diccionario, por lo que se requiere eliminar
	#Estructura resultante
		#'hastiar': [('Enojo\n', '0.629'), ('Repulsi\xf3n\n', '0.596')]
	return lexicon_sel

In [19]:
if (os.path.exists('lexicon_sel.pkl')):
    lexicon_sel_file = open ('lexicon_sel.pkl','rb')
    lexicon_sel = pickle.load(lexicon_sel_file)
else:
    lexicon_sel = load_sel()
    lexicon_sel_file = open ('lexicon_sel.pkl','wb')
    pickle.dump(lexicon_sel, lexicon_sel_file)
    lexicon_sel_file.close()

In [47]:
print(lexicon_sel['gustar'])

[('Alegría', '0.596')]


In [48]:
def getSELFeatures(cadenas, lexicon_sel):
	#'hastiar': [('Enojo\n', '0.629'), ('Repulsi\xf3n\n', '0.596')]
	features = []
	for cadena in cadenas:
		valor_alegria = 0.0
		valor_enojo = 0.0
		valor_miedo = 0.0
		valor_repulsion = 0.0
		valor_sorpresa = 0.0
		valor_tristeza = 0.0
		cadena_palabras = re.split('\s+', cadena)
		dic = {}
		for palabra in cadena_palabras:
			if palabra in lexicon_sel:
				caracteristicas = lexicon_sel[palabra]
				for emocion, valor in caracteristicas:
					if emocion == 'Alegría':
						valor_alegria = valor_alegria + float(valor)
					elif emocion == 'Tristeza':
						valor_tristeza = valor_tristeza + float(valor)
					elif emocion == 'Enojo':
						valor_enojo = valor_enojo + float(valor)
					elif emocion == 'Repulsión':
						valor_repulsion = valor_repulsion + float(valor)
					elif emocion == 'Miedo':
						valor_miedo = valor_miedo + float(valor)
					elif emocion == 'Sorpresa':
						valor_sorpresa = valor_sorpresa + float(valor)
		dic['__txt__'] = cadena_palabras
		dic['__alegria__'] = valor_alegria
		dic['__tristeza__'] = valor_tristeza
		dic['__enojo__'] = valor_enojo
		dic['__repulsion__'] = valor_repulsion
		dic['__miedo__'] = valor_miedo
		dic['__sorpresa__'] = valor_sorpresa
		
		#Esto es para los valores acumulados del mapeo a positivo (alegría + sorpresa) y negativo (enojo + miedo + repulsión + tristeza)
		dic['acumuladopositivo'] = dic['__alegria__'] + dic['__sorpresa__']
		dic['acumuladonegative'] = dic['__enojo__'] + dic['__miedo__'] + dic['__repulsion__'] + dic['__tristeza__']
		
		features.append (dic)
	
	
	return features

In [49]:
polaridad = getSELFeatures(train['Opinion'], lexicon_sel)
print("TEXTO")
print(train['Opinion'][7693])
print("POLARIDAD")
print (polaridad[0])

TEXTO
Aunque parece hipócrita arte Rivera ( ve zona segura ) , debo reconocer obras agradan . museo interesante simple hecho conocer primer hogar Rivera . Bastante fancy . chido si gusta ver cosas antigua .
POLARIDAD
{'__txt__': ['Lugar', 'acogedor', 'bueno', 'vacacionar', '.', 'Solo', 'servicio', 'taxi', 'pésimo', 'general', 'gusto', 'pase', 'increíble', ',', 'ademas', 'buena', 'atención', 'personal', ',', 'cuidadosos', 'huéspedes'], '__alegria__': 2.357, '__tristeza__': 0.0, '__enojo__': 0.0, '__repulsion__': 0.63, '__miedo__': 0.0, '__sorpresa__': 0.0, 'acumuladopositivo': 2.357, 'acumuladonegative': 0.63}


In [ ]:
polaridad_cadena_pos = np.array([polaridad[0]['acumuladopositivo']])
polaridad_cadena_neg = np.array([polaridad[0]['acumuladonegative']])
polaridad_cadena = np.concatenate((polaridad_cadena_pos, polaridad_cadena_neg), axis=0)

# Training ML models

## Without NLTK

In [40]:
x_train = train_vectorizado
y_train = train['Polarity']
x_test = test_vectorizado
y_test = test['Polarity']

In [42]:
print(x_train)

  (0, 14655)	0.21489746316734312
  (0, 7944)	0.471997395738744
  (0, 21122)	0.12006246219586392
  (0, 3158)	0.1833612387058041
  (0, 4457)	0.12337146589146565
  (0, 1127)	0.28279096649142316
  (0, 15127)	0.17597894759636737
  (0, 20622)	0.29679247422734784
  (0, 13956)	0.21073375479499623
  (0, 13409)	0.1616876357544541
  (0, 22722)	0.28158176130441925
  (0, 26900)	0.19231032064514206
  (0, 25474)	0.10502001810462905
  (0, 25984)	0.186939071252508
  (0, 28322)	0.3550624111534327
  (0, 4464)	0.14299134621099757
  (0, 882)	0.27811785862837407
  (0, 17224)	0.10996194124670956
  (1, 16604)	0.03337324003299682
  (1, 3160)	0.04261507365136779
  (1, 16839)	0.029917570321517924
  (1, 22010)	0.04715152987918691
  (1, 28266)	0.031329232263059996
  (1, 6360)	0.04363701517231048
  (1, 6584)	0.04153125683630938
  :	:
  (7999, 17740)	0.08456088603468845
  (7999, 16980)	0.1006780001891303
  (7999, 18227)	0.17679878263876778
  (7999, 21529)	0.15026410661354023
  (7999, 18121)	0.07766753391186947
  (79

In [35]:
clf_polarity = LogisticRegression(max_iter=10000)
clf_polarity.fit(x_train,y_train)
y_pred = clf_polarity.predict(x_test)

In [17]:
clf_bayes = MultinomialNB()
clf_bayes.fit(x_train, y_train)
y_pred = clf_bayes.predict(x_test)

### Lematizacion, stop words. Binarizado. Logistic Regression:

In [44]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       110
           2       0.00      0.00      0.00       136
           3       0.00      0.00      0.00       446
           4       0.58      1.00      0.73      1154
           5       0.00      0.00      0.00       154

    accuracy                           0.58      2000
   macro avg       0.12      0.20      0.15      2000
weighted avg       0.33      0.58      0.42      2000



c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Lematizacion, stop words. Frecuencia. Logistic Regression:

In [45]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       110
           2       0.00      0.00      0.00       136
           3       0.00      0.00      0.00       446
           4       0.58      1.00      0.73      1154
           5       0.00      0.00      0.00       154

    accuracy                           0.58      2000
   macro avg       0.12      0.20      0.15      2000
weighted avg       0.33      0.58      0.42      2000



c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Lematizacion, stop words. Tf-idf. Logistic Regression:

In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       110
           2       0.00      0.00      0.00       136
           3       0.00      0.00      0.00       446
           4       0.58      1.00      0.73      1154
           5       0.00      0.00      0.00       154

    accuracy                           0.58      2000
   macro avg       0.12      0.20      0.15      2000
weighted avg       0.33      0.58      0.42      2000



c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Lematizacion, stop words. Tf-idf. Multinomial Naive Bayes

In [47]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       110
           2       0.00      0.00      0.00       136
           3       0.00      0.00      0.00       446
           4       0.58      1.00      0.73      1154
           5       0.00      0.00      0.00       154

    accuracy                           0.58      2000
   macro avg       0.12      0.20      0.15      2000
weighted avg       0.33      0.58      0.42      2000



c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\sergi\miniconda3\envs\cursoNLP\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## With NLTK

### Lematizacion, stop words. Binarizado. Logistic Regression:

In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.68      0.21      0.32       109
           2       0.44      0.05      0.09       143
           3       0.43      0.27      0.33       409
           4       0.69      0.95      0.80      1201
           5       0.74      0.10      0.18       138

    accuracy                           0.65      2000
   macro avg       0.59      0.32      0.34      2000
weighted avg       0.62      0.65      0.58      2000



### Lematizacion, stop words. Frecuencia. Logistic Regression:

In [36]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.68      0.21      0.32       109
           2       0.44      0.05      0.09       143
           3       0.43      0.27      0.33       409
           4       0.69      0.95      0.80      1201
           5       0.74      0.10      0.18       138

    accuracy                           0.65      2000
   macro avg       0.59      0.32      0.34      2000
weighted avg       0.62      0.65      0.58      2000



In [37]:
cv_results = cross_validate(clf_polarity, x_train,y_train, cv=5, scoring='f1_macro', verbose = 3, n_jobs = -1)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   5 | elapsed:   20.7s remaining:   31.2s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:   21.2s finished


In [38]:
cv_results['test_score'].mean()

0.27621456039405234